bundles/conditional-availability/src/FondOfImpala/Shared/ConditionalAvailability/Transfer/contional_availability.transfer.xml
bundles/conditional-availability/src/FondOfImpala/Zed/ConditionalAvailability/Persistence/ConditionalAvailabilityEntityManager.php
bundles/conditional-availability/src/FondOfImpala/Zed/ConditionalAvailability/Persistence/ConditionalAvailabilityRepository.php
bundles/conditional-availability/src/FondOfImpala/Zed/ConditionalAvailability/Persistence/Propel/Schema/foi_conditional_availability.schema.xml

- add column `channel` to table `foi_conditional_availability`
- add unique constraint over `channel`, `warehouse_group` and `fk_product`
- prepare transfer definition for adding field `channel` to `ConditionalAvailabilityTransfer` & `ConditionalAvailabilityCriteriaFilterTransfer`
- ...

✨ Expand conditional availability with field channel

---

bundles/conditional-availability-product-page-search/src/FondOfImpala/Shared/ConditionalAvailabilityProductPageSearch/ConditionalAvailabilityProductPageSearchConfig.php
bundles/conditional-availability-product-page-search/src/FondOfImpala/Zed/ConditionalAvailabilityProductPageSearch/Business/ConditionalAvailabilityProductPageSearchBusinessFactory.php
bundles/conditional-availability-product-page-search/src/FondOfImpala/Zed/ConditionalAvailabilityProductPageSearch/Business/ConditionalAvailabilityProductPageSearchFacade.php
bundles/conditional-availability-product-page-search/src/FondOfImpala/Zed/ConditionalAvailabilityProductPageSearch/Business/Expander/ProductConcretePageSearchExpander.php
bundles/conditional-availability-product-page-search/src/FondOfImpala/Zed/ConditionalAvailabilityProductPageSearch/Business/ProductPage/ProductPageDataExpander.php
bundles/conditional-availability-product-page-search/src/FondOfImpala/Zed/ConditionalAvailabilityProductPageSearch/Business/Reader/ProductAbstractReader.php
bundles/conditional-availability-product-page-search/tests/FondOfImpala/Zed/ConditionalAvailabilityProductPageSearch/Business/ConditionalAvailabilityProductPageSearchBusinessFactoryTest.php
bundles/conditional-availability-product-page-search/tests/FondOfImpala/Zed/ConditionalAvailabilityProductPageSearch/Business/ConditionalAvailabilityProductPageSearchFacadeTest.php
bundles/conditional-availability-product-page-search/tests/FondOfImpala/Zed/ConditionalAvailabilityProductPageSearch/Business/Expander/ProductConcretePageSearchExpanderTest.php
bundles/conditional-availability-product-page-search/tests/FondOfImpala/Zed/ConditionalAvailabilityProductPageSearch/Business/ProductPage/ProductPageDataExpanderTest.php
bundles/conditional-availability-product-page-search/tests/FondOfImpala/Zed/ConditionalAvailabilityProductPageSearch/Business/Reader/ProductAbstractReaderTest.php
codeception.yml

- Implement Expanders, Reader, BusinessFactory, etc
- Implement Unit Test for the Implemented Expanders, Reader, BusinessFactory, etc

⚡️ Implement business logic for ConditionalAvailabilityProductPageSearch

---

bundles/conditional-availability-product-page-search/src/FondOfImpala/Shared/ConditionalAvailabilityProductPageSearch/Transfer/conditional_availability_product_page_search.transfer.xml
bundles/conditional-availability-product-page-search/src/FondOfImpala/Zed/ConditionalAvailabilityProductPageSearch/Communication/ConditionalAvailabilityProductPageSearchCommunicationFactory.php
bundles/conditional-availability-product-page-search/src/FondOfImpala/Zed/ConditionalAvailabilityProductPageSearch/Communication/Plugin/Event/Listener/ConditionalAvailabilityProductConcretePageSearchPublishListener.php
bundles/conditional-availability-product-page-search/src/FondOfImpala/Zed/ConditionalAvailabilityProductPageSearch/Communication/Plugin/Event/Subscriber/ConditionalAvailabilityProductPageSearchEventSubscriber.php
bundles/conditional-availability-product-page-search/src/FondOfImpala/Zed/ConditionalAvailabilityProductPageSearch/Communication/Plugin/ProductPageSearch/DataExpander/StockStatusDataLoadExpanderPlugin.php
bundles/conditional-availability-product-page-search/src/FondOfImpala/Zed/ConditionalAvailabilityProductPageSearch/Communication/Plugin/ProductPageSearch/DataLoader/StockStatusDataLoaderPlugin.php
bundles/conditional-availability-product-page-search/src/FondOfImpala/Zed/ConditionalAvailabilityProductPageSearch/Communication/Plugin/ProductPageSearch/Elasticsearch/StockStatusMapExpanderPlugin.php
bundles/conditional-availability-product-page-search/src/FondOfImpala/Zed/ConditionalAvailabilityProductPageSearch/Communication/Plugin/ProductPageSearch/ProductConcreteStockStatusPageDataExpanderPlugin.php
bundles/conditional-availability-product-page-search/src/FondOfImpala/Zed/ConditionalAvailabilityProductPageSearch/Communication/Plugin/ProductPageSearch/ProductConcreteStockStatusPageMapExpanderPlugin.php
bundles/conditional-availability-product-page-search/tests/FondOfImpala/Zed/ConditionalAvailabilityProductPageSearch/Communication/ConditionalAvailabilitySearchCommunicationFactoryTest.php
bundles/conditional-availability-product-page-search/tests/FondOfImpala/Zed/ConditionalAvailabilityProductPageSearch/Communication/Plugin/Event/Listener/ConditionalAvailabilityProductConcretePageSearchPublishListenerTest.php
bundles/conditional-availability-product-page-search/tests/FondOfImpala/Zed/ConditionalAvailabilityProductPageSearch/Communication/Plugin/Event/Subscriber/ConditionalAvailabilitySearchEventSubscriberTest.php
bundles/conditional-availability-product-page-search/tests/FondOfImpala/Zed/ConditionalAvailabilityProductPageSearch/Communication/Plugin/ProductPageSearch/DataExpander/StockStatusDataLoadExpanderPluginTest.php
bundles/conditional-availability-product-page-search/tests/FondOfImpala/Zed/ConditionalAvailabilityProductPageSearch/Communication/Plugin/ProductPageSearch/DataLoader/StockStatusDataLoaderPluginTest.php
bundles/conditional-availability-product-page-search/tests/FondOfImpala/Zed/ConditionalAvailabilityProductPageSearch/Communication/Plugin/ProductPageSearch/Elasticsearch/StockStatusMapExpanderPluginTest.php
bundles/conditional-availability-product-page-search/tests/FondOfImpala/Zed/ConditionalAvailabilityProductPageSearch/Communication/Plugin/ProductPageSearch/ProductConcreteStockStatusPageDataExpanderPluginTest.php
bundles/conditional-availability-product-page-search/tests/FondOfImpala/Zed/ConditionalAvailabilityProductPageSearch/Communication/Plugin/ProductPageSearch/ProductConcreteStockStatusPageMapExpanderPluginTest.php

- Implement Subscriber
- Implement Listener
- Implement DataLoader
- Implement Expanders
- Implement Unit Tests

⚡️Implement publish and synchronize for the stock status in ConditionalAvailabilityProductPageSearch

---

bundles/conditional-availability/src/FondOfImpala/Shared/ConditionalAvailability/Transfer/contional_availability.transfer.xml
bundles/conditional-availability/src/FondOfImpala/Zed/ConditionalAvailability/Persistence/ConditionalAvailabilityRepository.php

- add ids Property to the transfer object
-  Extend findConditionalAvailabilities with the ids filter

✨ Extend ConditionalAvailabilityCriteriaFilter  with ids filter

---

bundles/conditional-availability/src/FondOfImpala/Shared/ConditionalAvailability/Transfer/contional_availability.transfer.xml
bundles/conditional-availability/src/FondOfImpala/Zed/ConditionalAvailability/Business/ConditionalAvailabilityFacade.php
bundles/conditional-availability/src/FondOfImpala/Zed/ConditionalAvailability/Business/ConditionalAvailabilityFacadeInterface.php
bundles/conditional-availability/src/FondOfImpala/Zed/ConditionalAvailability/Persistence/ConditionalAvailabilityRepository.php
bundles/conditional-availability/src/FondOfImpala/Zed/ConditionalAvailability/Persistence/ConditionalAvailabilityRepositoryInterface.php
bundles/conditional-availability/tests/FondOfImpala/Zed/ConditionalAvailability/Business/ConditionalAvailabilityFacadeTest.php

- Implement Facade methods
- Implement Repository methods
- Implement Unit Test
- Code cleanup

✨️Implement methot to retrieve conditional availabilities by ids

---

bundles/conditional-availability-product-page-search/composer.json
dandelion.json

- release bundle/conditional-availability-product-page-search implementation
- add ne version for bundle/conditional-availability
- extend dependencies for the bundle/conditional-availability-product-page-search implementation

✨ release bundle/conditional-availability-product-page-search

---

bundles/customer-anonymizer-company-user-connector/src/FondOfImpala/Zed/CustomerAnonymizerCompanyUserConnector/Persistence/Propel/Mapper/CompanyUserMapper.php
dandelion.json

🐛Bugfix: map only available data

---

bundles/company-cart-search-rest-api/.github/workflows/main.yml
bundles/company-cart-search-rest-api/LICENSE
bundles/company-cart-search-rest-api/Makefile
bundles/company-cart-search-rest-api/codeception.yml
bundles/company-cart-search-rest-api/composer.json
bundles/company-cart-search-rest-api/phpstan.neon
bundles/company-cart-search-rest-api/src/FondOfImpala/Shared/CompanyCartSearchRestApi/CompanyCartSearchRestApiConstants.php
bundles/company-cart-search-rest-api/src/FondOfImpala/Zed/CompanyCartSearchRestApi/Business/CompanyCartSearchRestApiFacadeInterface.php
bundles/company-cart-search-rest-api/src/FondOfImpala/Zed/CompanyCartSearchRestApi/Business/Expander/QueryJoinCollectionExpanderInterface.php
bundles/company-cart-search-rest-api/src/FondOfImpala/Zed/CompanyCartSearchRestApi/Business/Filter/CompanyUuidFilterInterface.php
bundles/company-cart-search-rest-api/src/FondOfImpala/Zed/CompanyCartSearchRestApi/Business/Filter/IdCustomerFilterInterface.php
bundles/company-cart-search-rest-api/src/FondOfImpala/Zed/CompanyCartSearchRestApi/Business/Reader/CompanyReaderInterface.php
bundles/company-cart-search-rest-api/tests/_bootstrap.php
bundles/company-cart-search-rest-api/tests/_output/.gitignore
codeception.yml
composer.json

- add github action support for split repo
- add config files for phpstan, codeception, ...
- add composer.json for managing required (dev-)dependencies
- add glue, shared & zed layer to main autoload section in main composer.json
- include new bundle to main codeception.yml
- add contracts for filtering cart search result by company id (uuid)
- ...

✨ Initialize `company-cart-search-rest-api`-bundle

---

dandelion.json

- Add release version in `dandelion.json`

🔖release `collaborative-cart-search-rest-api` bundle

---

dandelion.json

- https://github.com/fond-of-impala/fond-of-impala/pull/144

🔖 update version for `conditional-availability-product-page-search`

---

dandelion.json

- Update  `conditional-availability-product-page-search` bundle version in dandelion.json

🔖 release `stock-status` trigger

---

bundles/conditional-availability-cart-connector/src/FondOfImpala/Zed/ConditionalAvailabilityCartConnector/Business/ConditionalAvailabilityCartConnectorBusinessFactory.php
bundles/conditional-availability-cart-connector/src/FondOfImpala/Zed/ConditionalAvailabilityCartConnector/Business/ConditionalAvailabilityCartConnectorFacade.php
bundles/conditional-availability-cart-connector/src/FondOfImpala/Zed/ConditionalAvailabilityCartConnector/Business/ConditionalAvailabilityCartConnectorFacadeInterface.php
bundles/conditional-availability-cart-connector/src/FondOfImpala/Zed/ConditionalAvailabilityCartConnector/Business/Filter/ConditionalAvailabilityPeriodsFilter.php
bundles/conditional-availability-cart-connector/src/FondOfImpala/Zed/ConditionalAvailabilityCartConnector/Business/Filter/ConditionalAvailabilityPeriodsFilterInterface.php
bundles/conditional-availability-cart-connector/src/FondOfImpala/Zed/ConditionalAvailabilityCartConnector/Business/Finder/IndexFinder.php
bundles/conditional-availability-cart-connector/src/FondOfImpala/Zed/ConditionalAvailabilityCartConnector/Business/Finder/IndexFinderInterface.php
bundles/conditional-availability-cart-connector/src/FondOfImpala/Zed/ConditionalAvailabilityCartConnector/Business/Reader/UnavailableSkuReader.php
bundles/conditional-availability-cart-connector/src/FondOfImpala/Zed/ConditionalAvailabilityCartConnector/Business/Reader/UnavailableSkuReaderInterface.php
bundles/conditional-availability-cart-connector/tests/FondOfImpala/Zed/ConditionalAvailabilityCartConnector/Business/ConditionalAvailabilityCartConnectorBusinessFactoryTest.php
bundles/conditional-availability-cart-connector/tests/FondOfImpala/Zed/ConditionalAvailabilityCartConnector/Business/ConditionalAvailabilityCartConnectorFacadeTest.php
bundles/conditional-availability-cart-connector/tests/FondOfImpala/Zed/ConditionalAvailabilityCartConnector/Business/Reader/UnavailableSkuReaderTest.php

- add logic for getting  unavailable skus by quote
- provide new logic by facade method
- add unit tests

✨ Add facade method to retrieve unavailable skus by quote

---

bundles/conditional-availability/src/FondOfImpala/Shared/ConditionalAvailability/Transfer/contional_availability.transfer.xml
bundles/conditional-availability/src/FondOfImpala/Zed/ConditionalAvailability/Business/ConditionalAvailabilityBusinessFactory.php
bundles/conditional-availability/src/FondOfImpala/Zed/ConditionalAvailability/Business/Generator/KeyGenerator.php
bundles/conditional-availability/src/FondOfImpala/Zed/ConditionalAvailability/Business/Generator/KeyGeneratorInterface.php
bundles/conditional-availability/src/FondOfImpala/Zed/ConditionalAvailability/Business/Model/ConditionalAvailabilityPeriodsPersister.php
bundles/conditional-availability/src/FondOfImpala/Zed/ConditionalAvailability/Persistence/Propel/Schema/foi_conditional_availability.schema.xml
bundles/conditional-availability/tests/FondOfImpala/Zed/ConditionalAvailability/Business/Generator/KeyGeneratorTest.php
bundles/conditional-availability/tests/FondOfImpala/Zed/ConditionalAvailability/Business/Model/ConditionalAvailabilityPeriodsPersisterTest.php
dandelion.json

- generate key by `now`, `startAt`, `endAt` & `fkConditionalAvailability`
- add database field `key` to `foi_conditional_availability`
- ...

✨ Add unique key to conditional availability period

---

bundles/product-image-grouping-product-page-search/src/FondOfImpala/Zed/ProductImageGroupingProductPageSearch/Communication/Plugin/ProductPageSearch/ProductImageGroupedPageDataLoaderExpanderPlugin.php
bundles/product-image-grouping-product-page-search/tests/FondOfImpala/Zed/ProductImageGroupingProductPageSearch/Communication/Plugin/ProductPageSearch/ProductImageGroupedPageDataLoaderExpanderPluginTest.php
dandelion.json

🐛 Swap if and else case for fallback group key

---

bundles/conditional-availability-page-search/composer.json
bundles/conditional-availability-page-search/src/FondOfImpala/Shared/ConditionalAvailabilityPageSearch/ConditionalAvailabilityPageSearchConstants.php
bundles/conditional-availability-page-search/src/FondOfImpala/Zed/ConditionalAvailabilityPageSearch/Communication/Plugin/PublisherExtension/ConditionalAvailabilityPeriodDeletePublisherPlugin.php
bundles/conditional-availability-page-search/src/FondOfImpala/Zed/ConditionalAvailabilityPageSearch/Communication/Plugin/PublisherExtension/ConditionalAvailabilityPeriodWritePublisherPlugin.php
bundles/conditional-availability-page-search/tests/FondOfImpala/Zed/ConditionalAvailabilityPageSearch/Communication/Plugin/PublisherExtension/ConditionalAvailabilityPeriodDeletePublisherPluginTest.php
bundles/conditional-availability-page-search/tests/FondOfImpala/Zed/ConditionalAvailabilityPageSearch/Communication/Plugin/PublisherExtension/ConditionalAvailabilityPeriodWritePublisherPluginTest.php
composer.json
dandelion.json

- add `spryker/publisher-extension`
- implement a plugin `ConditionalAvailabilityPeriodWritePublisherPlugin` for publishing conditional availability periods
- implement a plugin `ConditionalAvailabilityPeriodDeletePublisherPlugin` for unpublishing conditional availability periods
- add constant for own publish queue `publish.conditional_availability`
- add unit test
- ...

✨ Use publisher for conditional availability

---

bundles/company-users-bulk-rest-api/src/FondOfImpala/Zed/CompanyUsersBulkRestApi/Business/Expander/CompanyBusinessUnitToCompanyTransferExpander.php
bundles/company-users-bulk-rest-api/src/FondOfImpala/Zed/CompanyUsersBulkRestApi/Business/Expander/CompanyRolesToCompanyTransferExpander.php
bundles/company-users-bulk-rest-api/src/FondOfImpala/Zed/CompanyUsersBulkRestApi/Business/Manager/BulkManager.php
bundles/company-users-bulk-rest-api/tests/FondOfImpala/Zed/CompanyUsersBulkRestApi/Business/Expander/CompanyBusinessUnitToCompanyTransferExpanderTest.php
bundles/company-users-bulk-rest-api/tests/FondOfImpala/Zed/CompanyUsersBulkRestApi/Business/Expander/CompanyRolesToCompanyTransferExpanderTest.php
bundles/company-users-bulk-rest-api/tests/FondOfImpala/Zed/CompanyUsersBulkRestApi/Business/Manager/BulkManagerTest.php
dandelion.json

check data and skip single items instead of skip all bulk items

🧹 company users bulk rest api

---

bundles/company-users-bulk-rest-api-business-central-connector/composer.json
composer.json
dandelion.json

🧹 use fond-of-impala/navision-company instead of fond-of-spryker/navision-company

🧹 use fond-of-impala/navision-company

---

bundles/collaborative-cart-search-rest-api/.github/workflows/main.yml
bundles/conditional-availability-cart-connector/composer.json

fix typo in conditional-availability-cart-connector and add github action to collaborative-cart-search-rest-api bundle

fix typo in conditional-availability-cart-connector

---

bundles/product-image-grouping-product-page-search/src/FondOfImpala/Zed/ProductImageGroupingProductPageSearch/Business/Expander/ProductImageGroupPageDataExpander.php
bundles/product-image-grouping-product-page-search/src/FondOfImpala/Zed/ProductImageGroupingProductPageSearch/Business/Expander/ProductPageDataExpanderInterface.php
bundles/product-image-grouping-product-page-search/src/FondOfImpala/Zed/ProductImageGroupingProductPageSearch/Business/ProductImageGroupingProductPageSearchBusinessFactory.php
bundles/product-image-grouping-product-page-search/src/FondOfImpala/Zed/ProductImageGroupingProductPageSearch/Business/ProductImageGroupingProductPageSearchFacade.php
bundles/product-image-grouping-product-page-search/src/FondOfImpala/Zed/ProductImageGroupingProductPageSearch/Business/ProductImageGroupingProductPageSearchFacadeInterface.php
bundles/product-image-grouping-product-page-search/src/FondOfImpala/Zed/ProductImageGroupingProductPageSearch/Business/Validator/UrlValidator.php
bundles/product-image-grouping-product-page-search/src/FondOfImpala/Zed/ProductImageGroupingProductPageSearch/Business/Validator/UrlValidatorInterface.php
bundles/product-image-grouping-product-page-search/src/FondOfImpala/Zed/ProductImageGroupingProductPageSearch/Communication/Plugin/ProductPageSearch/ProductImageGroupMapExpanderPlugin.php
bundles/product-image-grouping-product-page-search/src/FondOfImpala/Zed/ProductImageGroupingProductPageSearch/Communication/Plugin/ProductPageSearch/ProductImageGroupedPageDataLoaderExpanderPlugin.php
bundles/product-image-grouping-product-page-search/tests/FondOfImpala/Zed/ProductImageGroupingProductPageSearch/Business/Expander/ProductImageGroupedPageDataExpanderTest.php
bundles/product-image-grouping-product-page-search/tests/FondOfImpala/Zed/ProductImageGroupingProductPageSearch/Business/Validator/UrlValidatorTest.php
bundles/product-image-grouping-product-page-search/tests/FondOfImpala/Zed/ProductImageGroupingProductPageSearch/Communication/Plugin/ProductPageSearch/ProductImageGroupedPageDataLoaderExpanderPluginTest.php
dandelion.json

add url validation for external product image urls

✨ product image group url validation

---

bundles/order-budgets-bulk-rest-api/composer.json
dandelion.json

- add required dependency to split repo

feat: release `fond-of-impala/order-budgets-bulk-rest-api`

---

bundles/conditional-availability-page-search/src/FondOfImpala/Client/ConditionalAvailabilityPageSearch/Plugin/SearchExtension/RawConditionalAvailabilityPeriodsResultFormatterPlugin.php
bundles/conditional-availability-page-search/src/FondOfImpala/Zed/ConditionalAvailabilityPageSearch/Business/ConditionalAvailabilityPageSearchFacade.php
bundles/conditional-availability-page-search/src/FondOfImpala/Zed/ConditionalAvailabilityPageSearch/Business/ConditionalAvailabilityPageSearchFacadeInterface.php
bundles/conditional-availability-page-search/src/FondOfImpala/Zed/ConditionalAvailabilityPageSearch/Business/Model/ConditionalAvailabilityPeriodPageSearchPublisher.php
bundles/conditional-availability-page-search/src/FondOfImpala/Zed/ConditionalAvailabilityPageSearch/Business/Model/ConditionalAvailabilityPeriodPageSearchPublisherInterface.php
bundles/conditional-availability-page-search/tests/FondOfImpala/Client/ConditionalAvailabilityPageSearch/ConditionalAvailabilityPageSearchClientTest.php
bundles/conditional-availability-page-search/tests/FondOfImpala/Client/ConditionalAvailabilityPageSearch/ConditionalAvailabilityPageSearchFactoryTest.php
bundles/conditional-availability-page-search/tests/FondOfImpala/Client/ConditionalAvailabilityPageSearch/Dependency/Client/ConditionalAvailabilityPageSearchToCustomerClientBridgeTest.php
bundles/conditional-availability-page-search/tests/FondOfImpala/Client/ConditionalAvailabilityPageSearch/Dependency/Client/ConditionalAvailabilityPageSearchToSearchClientBridgeTest.php
bundles/conditional-availability-page-search/tests/FondOfImpala/Zed/ConditionalAvailabilityPageSearch/Business/ConditionalAvailabilityPageSearchFacadeTest.php
dandelion.json

- allow to publish conditional availability periods by conditional availability ids
- allow to publish conditional availability periods by keys
- add rector fixes

feat: provide two additional publish methods

---

bundles/erp-order-cancellation-rest-api/composer.json
bundles/erp-order-cancellation-rest-api/src/FondOfImpala/Shared/ErpOrderCancellationRestApi/Transfer/erp_order_cancellation_rest_api.transfer.xml
bundles/erp-order-cancellation/composer.json
bundles/erp-order-cancellation/src/FondOfImpala/Shared/ErpOrderCancellation/Transfer/erp_order_cancellation.transfer.xml
bundles/erp-order-cancellation/src/FondOfImpala/Zed/ErpOrderCancellation/Persistence/Propel/Schema/foi_erp_order_cancellation.schema.xml
dandelion.json

- Change `line_id` to `varchar` in `schema.xml`
- Change 'lineId' to `string` in `transfer objects`
- Update versions in `dandelion.json`

feat: change `line_id` type to varchar/string

---

bundles/erp-order-cancellation-mail-connector/composer.json
bundles/erp-order-cancellation-mail-connector/src/FondOfImpala/Zed/ErpOrderCancellationMailConnector/Business/Model/Mail/MailHandler.php
bundles/erp-order-cancellation-mail-connector/tests/FondOfImpala/Zed/ErpOrderCancellationMailConnector/Business/ErpOrderCancellationMailConnectorBusinessFactoryTest.php
bundles/erp-order-cancellation-mail-connector/tests/FondOfImpala/Zed/ErpOrderCancellationMailConnector/Business/ErpOrderCancellationMailConnectorFacadeTest.php
bundles/erp-order-cancellation-mail-connector/tests/FondOfImpala/Zed/ErpOrderCancellationMailConnector/Business/Model/Mail/MailHandlerTest.php
bundles/erp-order-cancellation-mail-connector/tests/FondOfImpala/Zed/ErpOrderCancellationMailConnector/Communication/Plugin/ErpOrderCancellation/NotifyApprovedErpOrderCancellationPostTransactionPluginTest.php
bundles/erp-order-cancellation-mail-connector/tests/FondOfImpala/Zed/ErpOrderCancellationMailConnector/Communication/Plugin/ErpOrderCancellation/NotifyNewErpOrderCancellationPostTransactionPluginTest.php
bundles/erp-order-cancellation-mail-connector/tests/FondOfImpala/Zed/ErpOrderCancellationMailConnector/Communication/Plugin/ErpOrderCancellation/NotifyRejectedErpOrderCancellationPostTransactionPluginTest.php
bundles/erp-order-cancellation-mail-connector/tests/FondOfImpala/Zed/ErpOrderCancellationMailConnector/Communication/Plugin/Mail/NotifyApprovedErpOrderCancellationMailTypePluginTest.php
bundles/erp-order-cancellation-mail-connector/tests/FondOfImpala/Zed/ErpOrderCancellationMailConnector/Communication/Plugin/Mail/NotifyReadyErpOrderCancellationMailTypePluginTest.php
bundles/erp-order-cancellation-mail-connector/tests/FondOfImpala/Zed/ErpOrderCancellationMailConnector/Communication/Plugin/Mail/NotifyRejectedErpOrderCancellationMailTypePluginTest.php
bundles/erp-order-cancellation-mail-connector/tests/FondOfImpala/Zed/ErpOrderCancellationMailConnector/ErpOrderCancellationMailConnectorDependencyProviderTest.php
bundles/erp-order-cancellation-rest-api/.github/workflows/main.yml
bundles/permission-erp-order-cancellation-rest-api/tests/FondOfImpala/Zed/PermissionErpOrderCancellationRestApi/Communication/Plugin/ErpOrderCancellationRestApiExtension/ErpOrderCancellationCreatePermissionPluginTest.php
bundles/permission-erp-order-cancellation-rest-api/tests/FondOfImpala/Zed/PermissionErpOrderCancellationRestApi/Communication/Plugin/ErpOrderCancellationRestApiExtension/ErpOrderCancellationDeletePermissionPluginTest.php
bundles/permission-erp-order-cancellation-rest-api/tests/FondOfImpala/Zed/PermissionErpOrderCancellationRestApi/Communication/Plugin/ErpOrderCancellationRestApiExtension/ErpOrderCancellationUpdatePermissionPluginTest.php
bundles/permission-erp-order-cancellation-rest-api/tests/FondOfImpala/Zed/PermissionErpOrderCancellationRestApi/PermissionErpOrderCancellationRestApiDependencyProviderTest.php
codeception.yml
dandelion.json

- erp-order-cancellation-mail-connector
- permission-erp-order-cancellation
- also remove beta tags

chore: add unit tests

---

bundles/erp-order-cancellation-rest-api/src/FondOfImpala/Shared/ErpOrderCancellationRestApi/Transfer/erp_order_cancellation_rest_api.transfer.xml
bundles/erp-order-cancellation-rest-api/src/FondOfImpala/Zed/ErpOrderCancellationRestApi/Communication/Plugin/QueryExpander/StatesQueryExpanderPlugin.php
bundles/erp-order-cancellation-rest-api/tests/FondOfImpala/Zed/ErpOrderCancellationRestApi/Communication/Plugin/QueryExpander/StatesQueryExpanderPluginTest.php
dandelion.json

- Implement `QueryExpander`
- Extend transfer objects
- Implement Unit Test

feat: implement `States` filter

---

bundles/erp-order-cancellation-rest-api/src/FondOfImpala/Shared/ErpOrderCancellationRestApi/Transfer/erp_order_cancellation_rest_api.transfer.xml
bundles/erp-order-cancellation-rest-api/src/FondOfImpala/Zed/ErpOrderCancellationRestApi/Business/ErpOrderCancellationRestApiBusinessFactory.php
bundles/erp-order-cancellation-rest-api/src/FondOfImpala/Zed/ErpOrderCancellationRestApi/Business/Model/CancellationManager.php
bundles/erp-order-cancellation-rest-api/src/FondOfImpala/Zed/ErpOrderCancellationRestApi/Business/Model/Mapper/RestDataMapper.php
bundles/erp-order-cancellation-rest-api/tests/FondOfImpala/Zed/ErpOrderCancellationRestApi/Business/ErpOrderCancellationRestApiBusinessFactoryTest.php
bundles/erp-order-cancellation-rest-api/tests/FondOfImpala/Zed/ErpOrderCancellationRestApi/Business/Model/CancellationManagerTest.php
bundles/erp-order-cancellation-rest-api/tests/FondOfImpala/Zed/ErpOrderCancellationRestApi/Business/Model/Mapper/RestDataMapperTest.php
dandelion.json

- expand the `transfer` object
- expand the `restDataMapper`

feat: Expand `ErpOrderCancellationRestApi` with the `ErpOrder` Data

---

dandelion.json

This pull request includes version updates for two bundles in the `dandelion.json` file. The most important changes are:
Version updates:
* Updated the version of `erp-order-cancellation-rest-api` from `1.3.0` to `1.4.0`.
* Updated the version of `permission-erp-order-cancellation-rest-api` from `1.0.0` to `1.1.0`.

feat: update plugin versions
